### ISSUE TITLE
Speaker Images not scaled properly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#74]
At one point in the former changes the was a change that resulted in the speaker images scaled wrongly at some resolutions. Speaker images should always be in the ratio 1:1, but at some points the width is scaled down and the height is not scaled. See screenshot below.

![screenshot from 2016-03-12 22 26 00](https://cloud.githubusercontent.com/assets/1583873/13723483/11cfc5f0-e8a2-11e5-8b3f-449a872f0b87.png)

**Comment by mananwason** [comment]
@mariobehling now it looks okay to me. On Inspection as well the ratio is 300x300 only. So I think we can close this. Your views?
<img width="1439" alt="screen shot 2016-03-12 at 8 58 33 pm" src="https://cloud.githubusercontent.com/assets/10570249/13723781/3cfb1764-e895-11e5-99a7-2c73c7a94199.png">

**Comment by mariobehling** [comment]
@mananwason Issue is not solved. In different browser window sizes issue is there. 

There was no commit, so how can the issue be solved magically..

**Comment by singhksandeep25** [comment]
@mariobehling can you please specify the browser where you are seeing this bug? On firefox and chrome the images are fine.

**Comment by mariobehling** [comment]
@sandmanx Firefox and Chromium both show this bug. Try to increase/decrease the width of the browser window and you will see it.

**Comment by singhksandeep25** [comment]
@mariobehling I have fixed the issue and created a pull request. The problem was due to "height : 300px;" property in the .background-image class present in custom.css. Deleting it solves the problem.

Before:
![imageedit_1_2200141627](https://cloud.githubusercontent.com/assets/14184381/18707896/c50c08d0-8015-11e6-9444-894d0e070132.png)

After:
![imageedit_2_6961281843](https://cloud.githubusercontent.com/assets/14184381/18707906/d792ce1c-8015-11e6-8a97-0b9f333e8803.png)

**Comment by jigyasa-grover** [comment]
@sandmanx Kindly provide a link to your PR along with details and screenshots of desired changes. 
Cheers !

**Comment by jigyasa-grover** [comment]
Closing wrt PR https://github.com/fossasia/2016.fossasia.org/pull/112
